spring:
    datasource:
        password: 51280f386264f810be320763b64ef1caabb38ac761dfea32bead374e4ceef40b
        url: jdbc:postgresql://ec2-3-212-70-5.compute-1.amazonaws.com:5432/d58tcf1jtlm1a3?sslmode=require
        username: dsnxtxzaryfdem
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show-sql: true
springfox:
    documentation:
        swagger-ui:
            enabled: true

personagens:
  lista:
    - id: 1 # PROFESSOR FABIANO
      nome: "Fabiano"
      linhasDialogo:
        - mensagem: "Olá, jovem! Bem-vindo à aula da Introdução à Programação. Sou o professor Fabiano, estou aqui para ajudá-lo a mergulhar no mundo da lógica e da codificação. Como posso ajudá-lo?"
          opcoesResposta:
            - texto: "Ainda não tenho muito conhecimento sobre lógica de programação, poderia me dar um resumo?"
        - mensagem: "Basicamente, é a habilidade de resolver problemas de forma sistemática, dividindo-os em passos lógicos e compreensíveis para um computador. É como ensinar o computador a pensar! "
          opcoesResposta:
            - texto: "Poderia dar um exemplo de um problema resolvido com lógica de programação?"
        - mensagem: "Dado dois números inteiros, como podemos calcular a soma desses dois números?"
          imagem: 1
          opcoesResposta:
            - texto: "Saquei"
        - mensagem: "Agora vamos testar seus conhecimentos: Vamos escrever um programa que leia um número inteiro positivo e calcule o seu triplo. Como você preencheria a linha que está comentada?"
          opcoesResposta:
            - texto: "triplo = numero * 3;"
              id: 1
              correto: true
            - texto: "triplo = numero * 4;"
              id: 2
              correto: false
            - texto: "triplo = numero x 3;"
              id: 3
              correto: false
            - texto: "triplo = numero + numero + numero + numero;"
              id: 4
              correto: false
        - mensagem: "Vamos continuar o exercício. Vamos escrever um programa que leia um valor em polegadas e o converta para centímetros, considerando que uma polegada equivale a 2.54 cm."
          opcoesResposta:
            - texto: "centimetros = polegadas x 2.53;"
              id: 1
              correto: false
            - texto: "centimetros = polegadas * 2.54; "
              id: 2
              correto: true
            - texto: "centimetros = polegadas x 2.54;"
              id: 3
              correto: false
            - texto: "centimetros = polegada * 2.54;"
              id: 4
              correto: false
        - mensagem: "Ótimo! Você pode revisar os conteúdos que aprendemos aqui no seu caderno de anotações. Alguns colegas seus podem estar precisando de ajuda, seria interessante procurá-los pelo Campus da universidade e tentar auxiliá-los. Boa sorte!"
          opcoesResposta:
            - texto: "Finalizar conversa"

    - id: 2 # ALUNO LUCAS
      nome: "Lucas"
      linhasDialogo:
        - mensagem: "E aí, tudo bem? Meu nome é Lucas. Estou um pouco confuso com condicionais. Você já teve dificuldade em entender quando usar o if, else, else if? O professor Fabiano me deu essa anotação sobre o uso de condicionais."
          opcoesResposta:
            - texto: "Posso tentar te ajudar."
        - mensagem: "Estou meio travado em uma questão, que é a seguinte:  Preciso escrever um programa que leia um número inteiro e verifique se ele é positivo, qual opção abaixo resolveria a questão?"
          opcoesResposta:
            - texto: "if (numero > 0) "
              id: 1
              correto: true
            - texto: "if (numero = 0) {"
              id: 2
              correto: false
            - texto: "if (numero < 0) {"
              id: 3
              correto: false
            - texto: "if (numero <= 0) {"
              id: 4
              correto: false
        - mensagem: "Boa! A próxima questão é a seguinte: Temos que escrever um programa que leia um caractere e verifique se o mesmo é uma letra maiúscula, uma letra minúscula, um numeral ou nenhum dos tipos anteriores. Como podemos completar o código que está faltando? "
          opcoesResposta:
            - texto: "} else printf(\"Nenhum dos tipos anteriores\"); "
              id: 1
              correto: true
            - texto: "} else if printf(\"Nenhum dos tipos anteriores\");"
              id: 2
              correto: false
            - texto: "} if printf(\"Nenhum dos tipos anteriores\");"
              id: 3
              correto: false
            - texto: "} elif printf(\"Nenhum dos tipos anteriores\");"
              id: 4
              correto: false
        - mensagem: "Show, agora tudo se encaixa! valeu!"
          opcoesResposta:
            - texto: "Até logo"
    - id: 3 # ALUNA MARCELA
      nome: "Marcela"
      linhasDialogo:
        - mensagem: "Olá jovem, tudo certo? Sou a Marcela, o professor Fabiano me passou umas questões sobre loops, porém não estou conseguindo avançar, parece que estou em um “loop infinito”, hehe… Enfim, pode me ajudar a resolvê-las? Dá uma olhada nessa anotação sobre Loops!"
          opcoesResposta:
            - texto: "Te ajudo sim. Quais as questões?"
        - mensagem: "Bom, a primeira acredito que esta primeira seja para usar um “for”, porém não tenho certeza. A questão é: Escreva um programa que imprima todos os números inteiros entre 1 e 100 em ordem descendente. Como podemos preencher o trecho que está faltando?"
          opcoesResposta:
            - texto: "for (int numero = 1; numero >= 100; numero--) {"
              id: 1
              correto: false
            - texto: "for (int numer = 100; numero >= 1; numero--) {"
              id: 2
              correto: false
            - texto: "for (int numero = 100; numero >= 1; numero--) { "
              id: 3
              correto: true
            - texto: "for (int numero >= 100; numero >= 1; numero--) {"
              id: 4
              correto: false
        - mensagem: "Show! vamos já pra próxima questão: Escreva um programa que solicita ao usuário um número inteiro e imprime a tabuada desse número. O programa deve continuar pedindo números até que o usuário digite 0 para sair. Precisamos completar o trecho faltando:"
          opcoesResposta:
            - texto: "while (2) {"
              id: 1
              correto: false
            - texto: "while (TRUE) {"
              id: 2
              correto: false
            - texto: "while (1) {"
              id: 3
              correto: true
            - texto: "while (false) {"
              id: 4
              correto: false
        - mensagem: "A última: Escreva um programa que solicita ao usuário para inserir um número inteiro positivo e, em seguida, exibe uma contagem regressiva desse número até zero. Como as outras, precisamos preencher o trecho que falta: "
          opcoesResposta:
            - texto: "} while (numero <= 1);"
              id: 1
              correto: false
            - texto: "} while (numero > 0);"
              id: 2
              correto: false
            - texto: "} while (numero < 0);"
              id: 3
              correto: false
            - texto: "} while (numero <= 0);"
              id: 4
              correto: true
        - mensagem: "Acho que foi isso! conseguimos responder todas as questões, já estou entendendo um pouco mais desses loops. Muito obrigado pela ajuda!"
          opcoesResposta:
            - texto: "Tudo certo! vou dar uma olhada nas anotações sobre esse tema também!"
    - id: 4 # PROFESSORA JACQUELINE
      nome: "Jacqueline"
      linhasDialogo:
        - mensagem: "Olá, querido aluno! Sou a Jacqueline, mas pode me chamar de Jack! Hoje tenho um desafio de codificação para você. Estou ansiosa para ver como você vai resolver esse problema!"
          opcoesResposta:
            - texto: "Manda!"
        - mensagem: "Primeira questão: Escreva um programa que leia o valor do raio de uma esfera e determine o seu volume, o cálculo deve ser realizado através de um subprograma. Preencha o trecho que falta."
          opcoesResposta:
            - texto: "float calcularVolumeEsfra(float raio) {"
              id: 1
              correto: false
            - texto: "float calcularVolumeEsfera(float raio) {"
              id: 2
              correto: true
            - texto: "float calculaVolumeEsfera(float raio) {"
              id: 3
              correto: false
            - texto: "float calcularVolumeEsfera(float reio) {"
              id: 4
              correto: false
        - mensagem: "Boa, garoto. Agora a próxima questão é a seguinte: Escreva um programa que leia dois números inteiros M e N e verifique se N é múltiplo de M. Esta verificação deve ser realizada através de um subprograma. Já sabe o esquema né? Precisamos preencher o trecho comentado."
          opcoesResposta:
            - texto: "if (verificaMultiplo(M, N)) {"
              id: 1
              correto: false
            - texto: "if (verificarMultiplo(M, M)) {"
              id: 2
              correto: false
            - texto: "if (verificarMultiplo(A, N)) {"
              id: 3
              correto: false
            - texto: "if (verificarMultiplo(M, N)) {"
              id: 4
              correto: true
        - mensagem: "Muito bem jovem, você agora já tem uma ideia de como usar subprogramas quando estiver programando. Continue praticando!"
          opcoesResposta:
            - texto: "Obrigado professora!"
    - id: 5 # IAN A IA
      nome: "Ian"
      linhasDialogo:
        - mensagem: "Olá! Sou o Ian, sua INTELIGÊNCIA ARTIFICIAL para estudos em programação. Como posso ajudá-lo hoje?"
          opcoesResposta:
            - texto: "Qual conteúdo de programação você teria para me passar?"
        - mensagem: "Você já explorou estruturas de dados? Elas são como as ferramentas de um programador, permitindo organizar e manipular dados de maneira eficiente. Listas, filas, pilhas... há tantas opções para otimizar seus algoritmos e resolver problemas de forma elegante!"
          opcoesResposta:
            - texto: "Pilha? como assim?"
            - texto: "Que tipo de fila é essa?"
            - texto: "Lista de quê?"
            - texto: "OK, vamos praticar!"
        - mensagem: "PILHA - Sabe, pilhas são como uma pilha de pratos: o último prato colocado é o primeiro a ser retirado. Elas são ótimas para lidar com operações de 'último a entrar, primeiro a sair', como desfazer ações ou percorrer uma árvore de maneira recursiva!"
        - mensagem: "FILA - Pense em filas como uma linha de supermercado: o primeiro a chegar é o primeiro a ser atendido. Elas são perfeitas para simular situações da vida real, como processos em um sistema operacional ou pedidos em um restaurante movimentado!"
        - mensagem: "LISTA - Listas são como contêineres flexíveis, onde você pode armazenar uma variedade de dados e acessá-los facilmente. Elas são essenciais para organizar informações em ordem sequencial e facilitar a manipulação de dados em seus programas."
        
anotacoes:
  lista:
    - id: 1
      titulo: "COMANDOS DE ENTRADA E SAÍDA"
      texto: "para papapapapa para pa pa"
    - id: 2
      titulo: "CONDICIONAIS"
      texto: "para papapapapa para pa pa"
    - id: 3
      titulo: "COMANDOS DE REPETIÇÃO"
      texto: "para papapapapa para pa pa"
    - id: 4
      titulo: "SUBPROGRAMAS"
      texto: "para papapapapa para pa pa"
    - id: 5
      titulo: "ESTRUTURA DE DADOS"
      texto: "para papapapapa para pa pa"
    - id: 6
      titulo: "PONTEIROS"
      texto: "para papapapapa para pa pa"

insignias:
  lista:
    - id: 1
      nome: Iniciante promissor
      descricao: Acerte as 3 primeiras questões
      imagem: imagem.png

    - id: 2
      nome: Programador supremo
      descricao: Acerte todas as questões
      imagem: imagem.png

    - id: 3
      nome: Monitor de algoritmos
      descricao: Lidere o ranking em algum momento
      imagem: imagem.png

    - id: 4
      nome: Cavaleiro de bronze
      descricao: Esteja no TOP 3 do ranking em algum momento
      imagem: imagem.png

    - id: 5
      nome: Metade da jornada
      descricao: Consiga 50 pontos
      imagem: imagem.png

    - id: 6
      nome: Enciclopédia viva
      descricao: Complete o caderno de anotações
      imagem: imagem.png

    - id: 7
      nome: Diário do programador
      descricao: Adquira sua primeira anotação
      imagem: imagem.png

    - id: 8
      nome: Guardião do saber
      descricao: Preencha 4 anotações
      imagem: imagem.png

    - id: 9
      nome: Saindo da caverna
      descricao: Complete sua primeira interação com algum personagem
      imagem: imagem.png

    - id: 10
      nome: Tagarela compulsivo
      descricao: Converse com todos os personagens
      imagem: imagem.png

    - id: 11
      nome: A Skynet é real
      descricao: Converse com Ian, a IA
      imagem: imagem.png

    - id: 12
      nome: Rei da platina
      descricao: Libere todas as insígnias
      imagem: imagem.png
