spring:
    datasource:
        password: 51280f386264f810be320763b64ef1caabb38ac761dfea32bead374e4ceef40b
        url: jdbc:postgresql://ec2-3-212-70-5.compute-1.amazonaws.com:5432/d58tcf1jtlm1a3?sslmode=require
        username: dsnxtxzaryfdem
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show-sql: true
springfox:
    documentation:
        swagger-ui:
            enabled: true

personagens:
  lista:
    - id: 1 # PROFESSOR FABIANO
      linhasDialogo:
        - mensagem: "Olá, jovem! Bem-vindo à aula da Introdução à Programação. Estou aqui para ajudá-lo a mergulhar no mundo da lógica e da codificação. Como posso ajudá-lo?"
          opcoesResposta:
            - "Ainda não tenho muito conhecimento sobre lógica de programação, poderia me dar um resumo?"
        - mensagem: "Basicamente, é a habilidade de resolver problemas de forma sistemática, dividindo-os em passos lógicos e compreensíveis para um computador. É como ensinar o computador a pensar! "
          opcoesResposta:
            - "Poderia dar um exemplo de um problema resolvido com lógica de programação?"
        - mensagem: "Dado dois números inteiros, como podemos calcular a soma desses dois números?"
          imagem: 1
          opcoesResposta:
            - "Saquei"
        - mensagem: "Ótimo! Você pode revisar os conteúdos que aprendemos aqui no seu caderno de anotações. Alguns colegas seus podem estar precisando de ajuda, seria interessante procurá-los pelo Campus da universidade e tentar auxiliá-los. Boa sorte!"
          ultima: true
          opcoesResposta:
            - "Finalizar conversa"
      questoes:
        - enunciado: "Agora vamos testar seus conhecimentos: Vamos escrever um programa que leia um número inteiro positivo e calcule o seu triplo. Como você preencheria a linha que está comentada?"
          alternativas:
            - texto: "triplo = numero * 3;"
              id: 1
              correto: true
            - texto: "triplo = numero * 4;"
              id: 2
              correto: false
            - texto: "triplo = numero x 3;"
              id: 3
              correto: false
            - texto: "triplo = numero + numero + numero + numero;"
              id: 4
              correto: false
        - enunciado: "Vamos continuar o exercício. Vamos escrever um programa que leia um valor em polegadas e o converta para centímetros, considerando que uma polegada equivale a 2.54 cm."
          alternativas:
            - texto: "centimetros = polegadas x 2.53;"
              id: 1
              correto: false
            - texto: "centimetros = polegadas * 2.54; "
              id: 2
              correto: true
            - texto: "centimetros = polegadas x 2.54;"
              id: 3
              correto: false
            - texto: "centimetros = polegada * 2.54;"
              id: 4
              correto: false
    - id: 2 # ALUNO LUCAS
      linhasDialogo:
        - mensagem: "E aí, tudo bem? Meu nome é Lucas. Estou um pouco confuso com condicionais. Você já teve dificuldade em entender quando usar o if, else, else if? O professor Fabiano me deu essa anotação sobre o uso de condicionais."
          opcoesResposta:
            - "Posso tentar te ajudar."
        - mensagem: "Muito obrigado! acho que agora compreendi melhor o uso de condicionais. Lembre-se da anotação que o professor Fabiano nos passou, pode consultá-la sempre que quiser!"
          opcoesResposta:
            - "BOA"
          ultima: true
      questoes:
        - enunciado: "Estou meio travado em uma questão, que é a seguinte:  Preciso escrever um programa que leia um número inteiro e verifique se ele é positivo, qual opção abaixo resolveria a questão?"
          alternativas:
            - texto: "if (numero > 0) "
              id: 1
              correto: true
            - texto: "if (numero = 0) {"
              id: 2
              correto: false
            - texto: "if (numero < 0) {"
              id: 3
              correto: false
            - texto: "if (numero <= 0) {"
              id: 4
              correto: false
        - enunciado: "Boa! A próxima questão é a seguinte: Temos que escrever um programa que leia um caractere e verifique se o mesmo é uma letra maiúscula, uma letra minúscula, um numeral ou nenhum dos tipos anteriores. Como podemos completar o código que está faltando? "
          alternativas:
            - texto: "} else printf(\"Nenhum dos tipos anteriores\"); "
              id: 1
              correto: true
            - texto: "} else if printf(\"Nenhum dos tipos anteriores\");"
              id: 2
              correto: false
            - texto: "} if printf(\"Nenhum dos tipos anteriores\");"
              id: 3
              correto: false
            - texto: "} elif printf(\"Nenhum dos tipos anteriores\");"
              id: 4
              correto: false
anotacoes:
  lista:
    - id: 1
      titulo: "COMANDOS DE ENTRADA E SAÍDA"
      texto: "para papapapapa para pa pa"
    - id: 2
      titulo: "CONDICIONAIS"
      texto: "para papapapapa para pa pa"
    - id: 3
      titulo: "COMANDOS DE REPETIÇÃO"
      texto: "para papapapapa para pa pa"
    - id: 4
      titulo: "SUBPROGRAMAS"
      texto: "para papapapapa para pa pa"
    - id: 5
      titulo: "ESTRUTURA DE DADOS"
      texto: "para papapapapa para pa pa"
    - id: 6
      titulo: "PONTEIROS"
      texto: "para papapapapa para pa pa"